### ISSUE TITLE
Elegir fechas

### ISSUE THREAD

**Issue by pfg1008** [pfg1008/Trabajo-ISO-viaje-por-Europa#1]
Conversación para elegir las fechas del viaje.

**Comment by cag1023** [comment]
Creo que lo ideal sería irnos en verano una semana. ¿Qué os parece?

**Comment by pir1002** [comment]
Me parece bien, pero el mes de julio no puedo por que trabajo.

**Comment by pfg1008** [comment]
Yo también trabajo en julio, que os parece hacer el viaje en septiembre.

**Comment by cag1023** [comment]
Si! Antes de empezar las clases.

**Comment by pir1002** [comment]
Si perfecto, además en esas fechas los precios son más bajos.

**Comment by pfg1008** [comment]
Si tenemos que ir antes de que empiecen las clases, ¿vamos del 1 al 7 de septiembre?. En esas fechas aun hace bueno y estaríamos de vuelta para el inicio de curso.

**Comment by pir1002** [comment]
¡Sí del 1 al 7 perfecto!

**Comment by cag1023** [comment]
Genial, fechas decididas.

**Comment by cag1023** [comment]
Genial, fechas decididas.
