### ISSUE TITLE
Elegir destinos

### ISSUE THREAD

**Issue by pfg1008** [pfg1008/Trabajo-ISO-viaje-por-Europa#2]
Conversación para elegir destinos.

**Comment by pfg1008** [comment]
A mi me gastaría visitar Alemania.

**Comment by pir1002** [comment]
Yo quiero un destino con playa y calor

**Comment by pfg1008** [comment]
Si vamos a Alemania vamos a tener complicado encontrar esos destinos 😂

**Comment by cag1023** [comment]
yo quiero ir a Ámsterdam, que la prostitución es legal

**Comment by pir1002** [comment]
Pues descartado

**Comment by pir1002** [comment]
¿Y si vamos a Grecia?

**Comment by cag1023** [comment]
Si es mi sueño desde pequeña

**Comment by pir1002** [comment]
¡El mio también!, desde que vi Mamamia. Que bonita película

**Comment by pfg1008** [comment]
Pues entonces decidido, yo ya estuve hace unos años y me gusto mucho no me importaría repetir.

**Comment by pfg1008** [comment]
Yo también he visto MAMA MIA habéis visto la dos ?

**Comment by cag1023** [comment]
Si, pero la segunda es peor

**Comment by pir1002** [comment]
¡Claro! la segunda es mejor que la primera.

**Comment by cag1023** [comment]
Podemos ir a la isla en la que se grabó la pelicula!!!

**Comment by pir1002** [comment]
Planazo

**Comment by pfg1008** [comment]
Si perfecto un viaje por las islas

**Comment by cag1023** [comment]
Visitamos algunas famosas, y otras menos conocidas así no nos encontramos con tanto turista.

**Comment by pir1002** [comment]
Y también podemos ir a Atenas, siemprehe querido ver el Partenón en persona

**Comment by pfg1008** [comment]
Vale pues entonces ya hemos decidido que nos vamos a Grecia
![licensed-image](https://github.com/pfg1008/Trabajo-ISO-viaje-por-Europa/assets/162732199/c14ab69d-331a-47d9-be1a-2bd39c73c280)
