### ISSUE TITLE
Transporte

### ISSUE THREAD

**Issue by cag1023** [pfg1008/Trabajo-ISO-viaje-por-Europa#3]
Vamos ha decidir los diferentes medios de transporte que utilizaremos para desplazarnos entre las distintas ciudades.

**Comment by pir1002** [comment]
Podemos coger un Alsa a Madrid directo al aeropuerto para coger luego un vuelo a Atenas.

**Comment by pfg1008** [comment]
Ya he buscado los buses siempre suelen tener el mismo precio y te dejan directamente en la terminal.

![image](https://github.com/pfg1008/Trabajo-ISO-viaje-por-Europa/assets/162732199/c48d1551-0edd-49c5-a0b1-ea6a8186b963)

**Comment by cag1023** [comment]
He encontrado estos vuelos directos a Atenas, lo he comparado con otras fechas y en Septiembre es mucho más barato

Estos serían los de ida
![vuelos ida](https://github.com/pfg1008/Trabajo-ISO-viaje-por-Europa/assets/161066069/302ebf8e-12ee-4257-9df0-a149120641a6)

Y estos los de vuelta
![vuelos vuelta](https://github.com/pfg1008/Trabajo-ISO-viaje-por-Europa/assets/161066069/dfc3dca8-8747-4332-a280-cc6792093af0)

**Comment by pir1002** [comment]
¿Cómo nos vamos a desplazar entre las islas?

**Comment by pfg1008** [comment]
He visto que hay un bono para ir en ferri entre las islas pagando solo una vez pero lo tenemos que comprar alli.

**Comment by cag1023** [comment]
Okey mucho mejor, así nos pueden recomendar que nos saldría más rentable

**Comment by pfg1008** [comment]
Vale pues ya nos encargamos allí de buscarlo.
