### ISSUE TITLE
Alojamiento

### ISSUE THREAD

**Issue by cag1023** [pfg1008/Trabajo-ISO-viaje-por-Europa#4]
Dependiendo el destino elegido, veremos cual será el alojamiento más rentable.

**Comment by pfg1008** [comment]
Mi tope máximo de gasto para alojamiento es de 400 € espero que sea suficiente no hace falta que vayamos siempre a un hotel.

**Comment by cag1023** [comment]
He encontrado esta página en Internet recomendando los hoteles más económicos, echadle un vistazo.

https://www.voyagetips.com/es/ruta-islas-griegas-7-dias/

**Comment by pir1002** [comment]
También podemos buscar albergues, ya que al final vamos a estar moviendonos de un lado para otro.

**Comment by pfg1008** [comment]
Si estoy de acuerdo los albergues serian buena opción.

**Comment by cag1023** [comment]
Bueno pues como en los alojamientos estaremos poco tiempo cogemos lo más económico ya que lo importante del viaje es visitar las localidades y su gente.

**Comment by pir1002** [comment]
Me parece bien.
